language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gushtime/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true gushtime/react-test npm test

after_success:
  - docker build -t gushtime/multi-client ./client
  - docker build -t gushtime/multi-nginx ./nginx
  - docker build -t gushtime/multi-server ./server
  - docker build -t gushtime/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to docker hub
  - docker push gushtime/multi-client
  - docker push gushtime/multi-nginx
  - docker push gushtime/multi-server
  - docker push gushtime/multi-worker

  # Deploy AWS Settings
deploy:
  #edge: true ->> quick fix for bucket_name errors
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-786566844339
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY