blank_issues_enabled: true
contact_links:
  - name: Report a Bug
    about: Create a report of the issue you've encountered.
    url: https://github.com/evertonlperes/multi-docker/issues/new?template=xpto.yml&projects=evertonlperes%2Fmulti-docker%2F1&milestone=XPTO&labels=bug
