
name: project-bot
on:
  issues:
    types:
      - opened
      - reopened
permissions:
    issues: write
    repository-projects: read|write
jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - uses: skeet70/default-project-board-action@v1
        with:
          github_token: ${{ github.token }}
          repository: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          project: 1
